# Site settings
title: Supercool Engineering
email: dev@supercooldesign.co.uk
description: Engineering thoughts from the geekier side of Supercool.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://supercool.github.io" # the base hostname & protocol for your site
twitter_username: supercooldesign
github_username:  supercool

# Build settings
markdown: kramdown
