# Site settings
title: Engineering Supercool
email: dev@supercooldesign.co.uk
description: var_dump() from the geekier side of <a href="http://supercooldesign.co.uk" target="_blank">Supercool</a>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://supercool.github.io" # the base hostname & protocol for your site
twitter_username: supercooldesign
github_username:  supercool

# Build settings
markdown: kramdown
